import { auth, db } from './firebase-config.js';
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, writeBatch } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';

const root = document.querySelector('#admin-app');
const money = n => `${new Intl.NumberFormat('fr-DZ').format(Number(n || 0))} DA`;
const standardSizes = ['35','36','37','38','39','40','41','42','43','44','45','46'];
let products = [], orders = [], rates = [], editingId = null, subscriptions = [];

function loginView(message='') { root.innerHTML = `<section class="login"><div class="login-card"><span class="brand-kicker">Moda Afair · administration</span><h1>Gérer la boutique.</h1><p>Connectez-vous pour piloter le catalogue, les commandes et la livraison.</p><form id="login-form" class="form"><div class="field"><label for="email">Adresse e-mail</label><input id="email" type="email" autocomplete="email" required></div><div class="field"><label for="password">Mot de passe</label><input id="password" type="password" autocomplete="current-password" required></div><button class="btn-admin">Se connecter</button></form><p class="notice">${message}</p></div></section>`; document.querySelector('#login-form').addEventListener('submit', login); }
async function login(event) { event.preventDefault(); const email=document.querySelector('#email').value.trim(); const password=document.querySelector('#password').value; try { await signInWithEmailAndPassword(auth,email,password); } catch(error) { loginView('Identifiants incorrects ou compte non autorisé.'); } }
function shell(user) { root.innerHTML = `<div class="dashboard"><aside class="sidebar"><div class="sidebar-logo"><span>Back office</span><strong>MODA AFAIR</strong></div><nav class="side-nav"><button class="active" data-view="overview">Vue d’ensemble</button><button data-view="products">Produits</button><button data-view="orders">Commandes</button><button data-view="shipping">Livraison</button></nav><div class="sidebar-footer"><button class="btn-admin secondary" id="signout">Déconnexion</button></div></aside><section class="main-panel"><header class="topbar"><div class="admin-title"><span class="brand-kicker">Bonjour ${user.email}</span><h1 id="view-title">Vue d’ensemble</h1><p id="view-subtitle">Le pilotage simple de votre boutique.</p></div><span class="status-dot">Connecté à Firebase</span></header><div id="overview" class="admin-view active"></div><div id="products" class="admin-view"></div><div id="orders" class="admin-view"></div><div id="shipping" class="admin-view"></div></section></div><div class="toast-admin" id="toast"></div>`; document.querySelector('#signout').onclick=()=>signOut(auth); document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>showView(button.dataset.view)); renderAll(); }
function showView(view){ document.querySelectorAll('.admin-view').forEach(el=>el.classList.toggle('active',el.id===view)); document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view)); const titles={overview:['Vue d’ensemble','Le pilotage simple de votre boutique.'],products:['Produits','Ajoutez, modifiez ou retirez vos articles.'],orders:['Commandes','Suivez les commandes dès leur arrivée.'],shipping:['Livraison','Tarifs domicile et bureau par wilaya.']}; document.querySelector('#view-title').textContent=titles[view][0];document.querySelector('#view-subtitle').textContent=titles[view][1]; }
function toast(text){const el=document.querySelector('#toast');if(!el)return;el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function renderAll(){if(!document.querySelector('.dashboard'))return;renderOverview();renderProducts();renderOrders();renderShipping();}
function renderOverview(){const pending=orders.filter(o=>o.status==='Nouvelle').length;document.querySelector('#overview').innerHTML=`<div class="stats"><div class="stat"><span>Produits en ligne</span><strong>${products.length}</strong></div><div class="stat"><span>Nouvelles commandes</span><strong>${pending}</strong></div><div class="stat"><span>Wilayas configurées</span><strong>${rates.length}/58</strong></div></div><div class="panel"><div class="panel-head"><h2>Dernières commandes</h2><button class="small-btn" onclick="document.querySelector('[data-view=orders]').click()">Voir tout</button></div>${orders.length?orders.slice(0,5).map(orderMini).join(''):'<div class="empty-admin">Aucune commande reçue pour l’instant.</div>'}</div>`;}
function productForm(){return `<div class="panel"><div class="panel-head"><h2>${editingId?'Modifier le produit':'Ajouter un produit'}</h2>${editingId?'<button class="small-btn" id="cancel-edit">Annuler</button>':''}</div><form id="product-form" class="product-form"><div class="field"><label>Nom du produit</label><input name="name" required value="${editingId?escapeHtml(products.find(p=>p.id===editingId)?.name):''}"></div><div class="field"><label>Prix (DA)</label><input name="price" type="number" min="0" required value="${editingId?products.find(p=>p.id===editingId)?.price:''}"></div><div class="field"><label>Catégorie</label><select name="category"><option>Baskets</option><option>Vêtements</option></select></div><div class="field"><label>Couleurs (séparées par une virgule)</label><input name="colors" placeholder="Noir, Gris"></div><div class="field wide"><label>Description</label><textarea name="description" placeholder="Décrivez le produit…"></textarea></div><div class="field wide"><label>Photo du produit</label><input name="image" type="file" accept="image/*" ${editingId?'':'required'}><p class="upload-note">Import direct depuis PC ou téléphone — aucune URL à coller.</p></div><div class="field wide"><label>Tailles disponibles</label><div class="sizes">${standardSizes.map(size=>`<label class="size-check"><input type="checkbox" name="sizes" value="${size}" ${(!editingId&&['39','40','41','42','43'].includes(size))?'checked':''}>${size}</label>`).join('')}</div></div><div class="form-actions wide"><button class="btn-admin">${editingId?'Enregistrer les modifications':'Ajouter le produit'}</button></div></form></div>`}
function renderProducts(){const panel=document.querySelector('#products');if(!panel)return;panel.innerHTML=`${productForm()}<div class="panel"><div class="panel-head"><h2>Catalogue (${products.length})</h2>${products.length?'':'<button class="small-btn" id="import-catalog">Importer le catalogue actuel</button>'}</div><div class="products-list">${products.length?products.map(p=>`<article class="product-row"><img src="${p.image}" alt=""><div><strong>${escapeHtml(p.name)}</strong><span>${p.category} · ${money(p.price)} · ${(p.sizes||[]).join(', ')}</span></div><button class="small-btn" data-edit="${p.id}">Modifier</button><button class="small-btn delete" data-delete="${p.id}">Supprimer</button></article>`).join(''):'<div class="empty-admin">Le catalogue est vide. Importez les produits déjà en ligne pour pouvoir ensuite les modifier ou les supprimer.</div>'}</div></div>`;const editing=editingId&&products.find(p=>p.id===editingId);if(editing){panel.querySelector('[name=category]').value=editing.category||'Baskets';panel.querySelector('[name=colors]').value=(editing.colors||[]).join(', ');panel.querySelector('[name=description]').value=editing.description||'';panel.querySelectorAll('[name=sizes]').forEach(box=>box.checked=(editing.sizes||[]).includes(box.value));}panel.querySelector('#product-form').onsubmit=saveProduct;panel.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editingId=b.dataset.edit;renderProducts();});panel.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeProduct(b.dataset.delete));panel.querySelector('#cancel-edit')?.addEventListener('click',()=>{editingId=null;renderProducts()});panel.querySelector('#import-catalog')?.addEventListener('click',importCurrentCatalog);}
function slugify(value){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,55)}
async function importCurrentCatalog(){try{const source=await fetch('./app.js').then(r=>r.text());const match=source.match(/let products = (\[[\s\S]*?\n\]);\r?\n\r?\nconst money/);if(!match)throw new Error('Catalogue source introuvable.');const catalog=Function(`"use strict"; return (${match[1]});`)();const batch=writeBatch(db);catalog.forEach(product=>batch.set(doc(db,'products',product.id),product));await batch.commit();toast('Catalogue actuel importé.')}catch(error){toast(`Erreur : ${error.message}`)}}
async function compressImage(file){const image=await new Promise((resolve,reject)=>{const element=new Image();const url=URL.createObjectURL(file);element.onload=()=>{URL.revokeObjectURL(url);resolve(element)};element.onerror=()=>reject(new Error('Image illisible.'));element.src=url});const scale=Math.min(1,1200/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const result=canvas.toDataURL('image/jpeg',.76);if(result.length>680000)throw new Error('Image trop lourde après compression. Choisissez une photo plus légère.');return result}
async function saveProduct(event){event.preventDefault();const form=new FormData(event.currentTarget);const existing=editingId?products.find(p=>p.id===editingId):null;const name=form.get('name').trim(),file=form.get('image');let image=existing?.image||'';try{if(file&&file.size)image=await compressImage(file);const id=editingId||`${slugify(name)}-${Date.now().toString().slice(-5)}`;await setDoc(doc(db,'products',id),{name,price:Number(form.get('price')),category:form.get('category'),colors:String(form.get('colors')).split(',').map(v=>v.trim()).filter(Boolean),description:String(form.get('description')).trim(),sizes:form.getAll('sizes'),image,badge:existing?.badge||null,updatedAt:serverTimestamp()},{merge:true});editingId=null;toast('Produit enregistré.')}catch(error){toast(`Erreur : ${error.message}`)}}
async function removeProduct(id){if(!confirm('Supprimer ce produit du catalogue ?'))return;try{await deleteDoc(doc(db,'products',id));toast('Produit supprimé.')}catch(error){toast(`Erreur : ${error.message}`)}}
function orderMini(o){return `<article class="order-row"><div class="order-meta"><strong>${escapeHtml(o.customer?.name||'Client')}</strong><span>${o.customer?.wilayaName||'Wilaya'} · ${o.customer?.phone||''}</span></div><div>${money(o.total)}</div><div class="order-items">${(o.items||[]).map(i=>`${i.name||i.id} ×${i.qty}`).join('<br>')}</div><select class="order-status" data-status="${o.id}">${['Nouvelle','Confirmée','Expédiée','Livrée','Annulée'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></article>`}
function renderOrders(){const panel=document.querySelector('#orders');if(!panel)return;panel.innerHTML=`<div class="panel"><div class="panel-head"><h2>Toutes les commandes</h2></div><div class="orders-list">${orders.length?orders.map(orderMini).join(''):'<div class="empty-admin">Aucune commande reçue.</div>'}</div></div>`;panel.querySelectorAll('[data-status]').forEach(select=>select.onchange=async()=>{try{await updateDoc(doc(db,'orders',select.dataset.status),{status:select.value,updatedAt:serverTimestamp()});toast('Statut mis à jour.')}catch(error){toast(error.message)}})}
function renderShipping(){const panel=document.querySelector('#shipping');if(!panel)return;panel.innerHTML=`<div class="panel"><div class="panel-head"><h2>Prix de livraison</h2><div class="form-actions"><button class="small-btn" id="seed-rates">Initialiser les 58 wilayas</button><button class="btn-admin" id="save-rates">Enregistrer les tarifs</button></div></div><div class="table-wrap"><table class="rates"><thead><tr><th>Code</th><th>Wilaya</th><th>Domicile</th><th>Bureau</th></tr></thead><tbody>${rates.map(r=>`<tr data-rate="${r.code}"><td>${r.code}</td><td>${escapeHtml(r.name)}</td><td><input type="number" min="0" value="${r.domicile}" data-field="domicile"></td><td><input type="number" min="0" value="${r.bureau}" data-field="bureau"></td></tr>`).join('')}</tbody></table></div>${rates.length?'':'<div class="empty-admin">Initialisez les tarifs de livraison fournis afin de les gérer ici.</div>'}</div>`;panel.querySelector('#save-rates')?.addEventListener('click',saveRates);panel.querySelector('#seed-rates')?.addEventListener('click',seedRates)}
async function seedRates(){try{const source=await fetch('./app.js').then(r=>r.text());const match=source.match(/(?:const|let) deliveryRates = (\[[\s\S]*?\])\.map/);if(!match)throw new Error('Tarifs source introuvables.');const raw=JSON.parse(match[1]);const batch=writeBatch(db);raw.forEach(([name,domicile,bureau],index)=>batch.set(doc(db,'deliveryRates',String(index+1).padStart(2,'0')),{name,domicile,bureau}));await batch.commit();toast('Les 58 wilayas sont prêtes.')}catch(error){toast(`Erreur : ${error.message}`)}}
async function saveRates(){try{const batch=writeBatch(db);document.querySelectorAll('[data-rate]').forEach(row=>batch.set(doc(db,'deliveryRates',row.dataset.rate),{domicile:Number(row.querySelector('[data-field=domicile]').value),bureau:Number(row.querySelector('[data-field=bureau]').value)},{merge:true}));await batch.commit();toast('Tarifs enregistrés.')}catch(error){toast(`Erreur : ${error.message}`)}}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function startData(){subscriptions.forEach(off=>off());subscriptions=[];subscriptions.push(onSnapshot(collection(db,'products'),snap=>{products=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>a.name.localeCompare(b.name));renderAll()}));subscriptions.push(onSnapshot(query(collection(db,'orders'),orderBy('createdAt','desc')),snap=>{orders=snap.docs.map(d=>({id:d.id,...d.data()}));renderAll()},()=>{orders=[];renderAll()}));subscriptions.push(onSnapshot(collection(db,'deliveryRates'),snap=>{rates=snap.docs.map(d=>({code:d.id,...d.data()})).sort((a,b)=>a.code.localeCompare(b.code));renderAll()}));}
onAuthStateChanged(auth,async user=>{if(!user){subscriptions.forEach(off=>off());subscriptions=[];loginView();return;}try{const admin=await getDoc(doc(db,'admins',user.uid));if(!admin.exists()){await signOut(auth);loginView('Ce compte n’a pas encore les droits administrateur.');return;}shell(user);startData();}catch(error){loginView('La base Firebase doit être activée avant la première connexion.');}});
